# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'WhereYouAt' do
pod 'Firebase', '>=2.5.1'
pod 'Google/SignIn'
pod 'SwiftyJSON'
pod 'ChameleonFramework'
end

target 'WhereYouAtTests' do

end

target 'WhereYouAtUITests' do

end

